sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "9"
before_install:
    - "npm config set spin false"
    - "npm install -g npm@^5"
    - "npm install -g codecov"
install:
    - npm install
script:
    - npm run test
build: 
    - npm run build
after_success:
  - codecov
